[Thu May 09 19:33:02.455830 2019] [auth_digest:notice] [pid 5886] AH01757: generating secret for digest authentication ...
[Thu May 09 19:33:02.458702 2019] [lbmethod_heartbeat:notice] [pid 5886] AH02282: No slotmem from mod_heartmonitor
[Thu May 09 19:33:02.461775 2019] [mpm_prefork:notice] [pid 5886] AH00163: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_wsgi/3.4 Python/2.7.5 configured -- resuming normal operations
[Thu May 09 19:33:02.461816 2019] [core:notice] [pid 5886] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Thu May 09 19:34:19.249618 2019] [mpm_prefork:notice] [pid 5886] AH00170: caught SIGWINCH, shutting down gracefully
[Thu May 09 19:34:20.416157 2019] [core:notice] [pid 5967] SELinux policy enabled; httpd running as context system_u:system_r:httpd_t:s0
[Thu May 09 19:34:20.417789 2019] [suexec:notice] [pid 5967] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Thu May 09 19:34:20.469031 2019] [auth_digest:notice] [pid 5967] AH01757: generating secret for digest authentication ...
[Thu May 09 19:34:20.470584 2019] [lbmethod_heartbeat:notice] [pid 5967] AH02282: No slotmem from mod_heartmonitor
[Thu May 09 19:34:20.485512 2019] [mpm_prefork:notice] [pid 5967] AH00163: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_wsgi/3.4 Python/2.7.5 configured -- resuming normal operations
[Thu May 09 19:34:20.485628 2019] [core:notice] [pid 5967] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Thu May 09 19:34:26.242226 2019] [:error] [pid 5968] [client 10.10.3.2:40754] mod_wsgi (pid=5968, process='', application='www1.ice.nuie.nagoya-u.ac.jp|'): Failed to parse WSGI script file '/var/www/cgi-bin/ex6-1last.py'.
[Thu May 09 19:34:26.242360 2019] [:error] [pid 5968] [client 10.10.3.2:40754] mod_wsgi (pid=5968): Exception occurred processing WSGI script '/var/www/cgi-bin/ex6-1last.py'.
[Thu May 09 19:34:26.242515 2019] [:error] [pid 5968] [client 10.10.3.2:40754]   File "/var/www/cgi-bin/ex6-1last.py", line 144
[Thu May 09 19:34:26.242544 2019] [:error] [pid 5968] [client 10.10.3.2:40754] SyntaxError: Non-ASCII character '\\xe3' in file /var/www/cgi-bin/ex6-1last.py on line 144, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
[Thu May 09 19:35:14.312885 2019] [mpm_prefork:notice] [pid 5967] AH00170: caught SIGWINCH, shutting down gracefully
[Thu May 09 19:35:15.477439 2019] [core:notice] [pid 6015] SELinux policy enabled; httpd running as context system_u:system_r:httpd_t:s0
[Thu May 09 19:35:15.479071 2019] [suexec:notice] [pid 6015] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Thu May 09 19:35:15.538732 2019] [auth_digest:notice] [pid 6015] AH01757: generating secret for digest authentication ...
[Thu May 09 19:35:15.540737 2019] [lbmethod_heartbeat:notice] [pid 6015] AH02282: No slotmem from mod_heartmonitor
[Thu May 09 19:35:15.555625 2019] [mpm_prefork:notice] [pid 6015] AH00163: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_wsgi/3.4 Python/2.7.5 configured -- resuming normal operations
[Thu May 09 19:35:15.555775 2019] [core:notice] [pid 6015] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Thu May 09 19:35:16.806804 2019] [:error] [pid 6016] [client 10.10.3.2:40764] mod_wsgi (pid=6016, process='', application='www1.ice.nuie.nagoya-u.ac.jp|'): Failed to parse WSGI script file '/var/www/cgi-bin/ex6-1last.py'.
[Thu May 09 19:35:16.806938 2019] [:error] [pid 6016] [client 10.10.3.2:40764] mod_wsgi (pid=6016): Exception occurred processing WSGI script '/var/www/cgi-bin/ex6-1last.py'.
[Thu May 09 19:35:16.807093 2019] [:error] [pid 6016] [client 10.10.3.2:40764]   File "/var/www/cgi-bin/ex6-1last.py", line 145
[Thu May 09 19:35:16.807121 2019] [:error] [pid 6016] [client 10.10.3.2:40764] SyntaxError: Non-ASCII character '\\xe3' in file /var/www/cgi-bin/ex6-1last.py on line 145, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
[Thu May 09 19:45:05.091024 2019] [mpm_prefork:notice] [pid 6015] AH00170: caught SIGWINCH, shutting down gracefully
[Thu May 09 19:45:06.262778 2019] [core:notice] [pid 6094] SELinux policy enabled; httpd running as context system_u:system_r:httpd_t:s0
[Thu May 09 19:45:06.264525 2019] [suexec:notice] [pid 6094] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Thu May 09 19:45:06.316079 2019] [auth_digest:notice] [pid 6094] AH01757: generating secret for digest authentication ...
[Thu May 09 19:45:06.317618 2019] [lbmethod_heartbeat:notice] [pid 6094] AH02282: No slotmem from mod_heartmonitor
[Thu May 09 19:45:06.331150 2019] [mpm_prefork:notice] [pid 6094] AH00163: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_wsgi/3.4 Python/2.7.5 configured -- resuming normal operations
[Thu May 09 19:45:06.331253 2019] [core:notice] [pid 6094] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Thu May 09 19:45:10.562911 2019] [:error] [pid 6095] [client 10.10.3.2:40808] mod_wsgi (pid=6095, process='', application='www1.ice.nuie.nagoya-u.ac.jp|'): Failed to parse WSGI script file '/var/www/cgi-bin/ex6.py'.
[Thu May 09 19:45:10.563049 2019] [:error] [pid 6095] [client 10.10.3.2:40808] mod_wsgi (pid=6095): Exception occurred processing WSGI script '/var/www/cgi-bin/ex6.py'.
[Thu May 09 19:45:10.563208 2019] [:error] [pid 6095] [client 10.10.3.2:40808]   File "/var/www/cgi-bin/ex6.py", line 225
[Thu May 09 19:45:10.563237 2019] [:error] [pid 6095] [client 10.10.3.2:40808] SyntaxError: Non-ASCII character '\\xe2' in file /var/www/cgi-bin/ex6.py on line 225, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
[Thu May 09 19:46:49.113993 2019] [mpm_prefork:notice] [pid 6094] AH00170: caught SIGWINCH, shutting down gracefully
[Thu May 09 19:46:50.274319 2019] [core:notice] [pid 6135] SELinux policy enabled; httpd running as context system_u:system_r:httpd_t:s0
[Thu May 09 19:46:50.275960 2019] [suexec:notice] [pid 6135] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Thu May 09 19:46:50.354521 2019] [auth_digest:notice] [pid 6135] AH01757: generating secret for digest authentication ...
[Thu May 09 19:46:50.357285 2019] [lbmethod_heartbeat:notice] [pid 6135] AH02282: No slotmem from mod_heartmonitor
[Thu May 09 19:46:50.369457 2019] [mpm_prefork:notice] [pid 6135] AH00163: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_wsgi/3.4 Python/2.7.5 configured -- resuming normal operations
[Thu May 09 19:46:50.369570 2019] [core:notice] [pid 6135] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Thu May 09 19:46:51.832892 2019] [:error] [pid 6136] [client 10.10.3.2:40820] mod_wsgi (pid=6136): Exception occurred processing WSGI script '/var/www/cgi-bin/ex6.py'.
[Thu May 09 19:46:51.832994 2019] [:error] [pid 6136] [client 10.10.3.2:40820] Traceback (most recent call last):
[Thu May 09 19:46:51.833034 2019] [:error] [pid 6136] [client 10.10.3.2:40820]   File "/var/www/cgi-bin/ex6.py", line 122, in application
[Thu May 09 19:46:51.833266 2019] [:error] [pid 6136] [client 10.10.3.2:40820]     make_database()
[Thu May 09 19:46:51.833286 2019] [:error] [pid 6136] [client 10.10.3.2:40820]   File "/var/www/cgi-bin/ex6.py", line 11, in make_database
[Thu May 09 19:46:51.833319 2019] [:error] [pid 6136] [client 10.10.3.2:40820]     con = sqlite3.connect(dbname)
[Thu May 09 19:46:51.833352 2019] [:error] [pid 6136] [client 10.10.3.2:40820] OperationalError: unable to open database file
[Thu May 09 19:46:55.723994 2019] [:error] [pid 6140] [client 10.10.3.2:40824] mod_wsgi (pid=6140): Exception occurred processing WSGI script '/var/www/cgi-bin/ex6.py'.
[Thu May 09 19:46:55.724095 2019] [:error] [pid 6140] [client 10.10.3.2:40824] Traceback (most recent call last):
[Thu May 09 19:46:55.724135 2019] [:error] [pid 6140] [client 10.10.3.2:40824]   File "/var/www/cgi-bin/ex6.py", line 122, in application
[Thu May 09 19:46:55.724375 2019] [:error] [pid 6140] [client 10.10.3.2:40824]     make_database()
[Thu May 09 19:46:55.724397 2019] [:error] [pid 6140] [client 10.10.3.2:40824]   File "/var/www/cgi-bin/ex6.py", line 11, in make_database
[Thu May 09 19:46:55.724431 2019] [:error] [pid 6140] [client 10.10.3.2:40824]     con = sqlite3.connect(dbname)
[Thu May 09 19:46:55.724465 2019] [:error] [pid 6140] [client 10.10.3.2:40824] OperationalError: unable to open database file
[Thu May 09 19:55:34.073199 2019] [mpm_prefork:notice] [pid 6135] AH00170: caught SIGWINCH, shutting down gracefully
[Thu May 09 19:55:35.239263 2019] [core:notice] [pid 6226] SELinux policy enabled; httpd running as context system_u:system_r:httpd_t:s0
[Thu May 09 19:55:35.242697 2019] [suexec:notice] [pid 6226] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Thu May 09 19:55:35.319670 2019] [auth_digest:notice] [pid 6226] AH01757: generating secret for digest authentication ...
[Thu May 09 19:55:35.321469 2019] [lbmethod_heartbeat:notice] [pid 6226] AH02282: No slotmem from mod_heartmonitor
[Thu May 09 19:55:35.334708 2019] [mpm_prefork:notice] [pid 6226] AH00163: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_wsgi/3.4 Python/2.7.5 configured -- resuming normal operations
[Thu May 09 19:55:35.334801 2019] [core:notice] [pid 6226] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Thu May 09 19:55:37.520320 2019] [:error] [pid 6227] [client 10.10.3.2:40838] mod_wsgi (pid=6227): Exception occurred processing WSGI script '/var/www/cgi-bin/ex6.py'.
[Thu May 09 19:55:37.520421 2019] [:error] [pid 6227] [client 10.10.3.2:40838] Traceback (most recent call last):
[Thu May 09 19:55:37.520471 2019] [:error] [pid 6227] [client 10.10.3.2:40838]   File "/var/www/cgi-bin/ex6.py", line 122, in application
[Thu May 09 19:55:37.520731 2019] [:error] [pid 6227] [client 10.10.3.2:40838]     make_database()
[Thu May 09 19:55:37.520760 2019] [:error] [pid 6227] [client 10.10.3.2:40838]   File "/var/www/cgi-bin/ex6.py", line 11, in make_database
[Thu May 09 19:55:37.520794 2019] [:error] [pid 6227] [client 10.10.3.2:40838]     con = sqlite3.connect(dbname)
[Thu May 09 19:55:37.520829 2019] [:error] [pid 6227] [client 10.10.3.2:40838] OperationalError: unable to open database file
[Thu May 09 20:02:59.392254 2019] [mpm_prefork:notice] [pid 6226] AH00170: caught SIGWINCH, shutting down gracefully
[Thu May 09 20:03:00.545648 2019] [core:notice] [pid 6320] SELinux policy enabled; httpd running as context system_u:system_r:httpd_t:s0
[Thu May 09 20:03:00.547287 2019] [suexec:notice] [pid 6320] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Thu May 09 20:03:00.625139 2019] [auth_digest:notice] [pid 6320] AH01757: generating secret for digest authentication ...
[Thu May 09 20:03:00.628163 2019] [lbmethod_heartbeat:notice] [pid 6320] AH02282: No slotmem from mod_heartmonitor
[Thu May 09 20:03:00.642489 2019] [mpm_prefork:notice] [pid 6320] AH00163: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_wsgi/3.4 Python/2.7.5 configured -- resuming normal operations
[Thu May 09 20:03:00.642592 2019] [core:notice] [pid 6320] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Thu May 09 20:03:02.017181 2019] [:error] [pid 6322] [client 10.10.3.2:40844] mod_wsgi (pid=6322): Exception occurred processing WSGI script '/var/www/cgi-bin/ex6.py'.
[Thu May 09 20:03:02.017285 2019] [:error] [pid 6322] [client 10.10.3.2:40844] Traceback (most recent call last):
[Thu May 09 20:03:02.017325 2019] [:error] [pid 6322] [client 10.10.3.2:40844]   File "/var/www/cgi-bin/ex6.py", line 122, in application
[Thu May 09 20:03:02.017562 2019] [:error] [pid 6322] [client 10.10.3.2:40844]     make_database()
[Thu May 09 20:03:02.017584 2019] [:error] [pid 6322] [client 10.10.3.2:40844]   File "/var/www/cgi-bin/ex6.py", line 11, in make_database
[Thu May 09 20:03:02.017618 2019] [:error] [pid 6322] [client 10.10.3.2:40844]     con = sqlite3.connect(dbname)
[Thu May 09 20:03:02.017669 2019] [:error] [pid 6322] [client 10.10.3.2:40844] OperationalError: unable to open database file
[Thu May 09 20:03:04.287253 2019] [:error] [pid 6321] [client 10.10.3.2:40846] mod_wsgi (pid=6321): Exception occurred processing WSGI script '/var/www/cgi-bin/ex6.py'.
[Thu May 09 20:03:04.287355 2019] [:error] [pid 6321] [client 10.10.3.2:40846] Traceback (most recent call last):
[Thu May 09 20:03:04.287396 2019] [:error] [pid 6321] [client 10.10.3.2:40846]   File "/var/www/cgi-bin/ex6.py", line 122, in application
[Thu May 09 20:03:04.287670 2019] [:error] [pid 6321] [client 10.10.3.2:40846]     make_database()
[Thu May 09 20:03:04.287701 2019] [:error] [pid 6321] [client 10.10.3.2:40846]   File "/var/www/cgi-bin/ex6.py", line 11, in make_database
[Thu May 09 20:03:04.287738 2019] [:error] [pid 6321] [client 10.10.3.2:40846]     con = sqlite3.connect(dbname)
[Thu May 09 20:03:04.287773 2019] [:error] [pid 6321] [client 10.10.3.2:40846] OperationalError: unable to open database file
[Thu May 09 20:04:02.930287 2019] [mpm_prefork:notice] [pid 6320] AH00170: caught SIGWINCH, shutting down gracefully
[Thu May 09 20:04:04.082424 2019] [core:notice] [pid 6338] SELinux policy enabled; httpd running as context system_u:system_r:httpd_t:s0
[Thu May 09 20:04:04.084044 2019] [suexec:notice] [pid 6338] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Thu May 09 20:04:04.135287 2019] [auth_digest:notice] [pid 6338] AH01757: generating secret for digest authentication ...
[Thu May 09 20:04:04.137012 2019] [lbmethod_heartbeat:notice] [pid 6338] AH02282: No slotmem from mod_heartmonitor
[Thu May 09 20:04:04.147408 2019] [mpm_prefork:notice] [pid 6338] AH00163: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_wsgi/3.4 Python/2.7.5 configured -- resuming normal operations
[Thu May 09 20:04:04.147516 2019] [core:notice] [pid 6338] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Thu May 09 20:04:05.353903 2019] [:error] [pid 6340] [client 10.10.3.2:40848] mod_wsgi (pid=6340): Exception occurred processing WSGI script '/var/www/cgi-bin/ex6.py'.
[Thu May 09 20:04:05.354007 2019] [:error] [pid 6340] [client 10.10.3.2:40848] Traceback (most recent call last):
[Thu May 09 20:04:05.354049 2019] [:error] [pid 6340] [client 10.10.3.2:40848]   File "/var/www/cgi-bin/ex6.py", line 122, in application
[Thu May 09 20:04:05.354292 2019] [:error] [pid 6340] [client 10.10.3.2:40848]     make_database()
[Thu May 09 20:04:05.354314 2019] [:error] [pid 6340] [client 10.10.3.2:40848]   File "/var/www/cgi-bin/ex6.py", line 11, in make_database
[Thu May 09 20:04:05.354349 2019] [:error] [pid 6340] [client 10.10.3.2:40848]     con = sqlite3.connect(dbname)
[Thu May 09 20:04:05.354383 2019] [:error] [pid 6340] [client 10.10.3.2:40848] OperationalError: unable to open database file
[Thu May 09 20:04:17.294889 2019] [mpm_prefork:notice] [pid 6338] AH00170: caught SIGWINCH, shutting down gracefully
[Thu May 09 20:04:18.444590 2019] [core:notice] [pid 6356] SELinux policy enabled; httpd running as context system_u:system_r:httpd_t:s0
[Thu May 09 20:04:18.446203 2019] [suexec:notice] [pid 6356] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Thu May 09 20:04:18.523320 2019] [auth_digest:notice] [pid 6356] AH01757: generating secret for digest authentication ...
[Thu May 09 20:04:18.525516 2019] [lbmethod_heartbeat:notice] [pid 6356] AH02282: No slotmem from mod_heartmonitor
[Thu May 09 20:04:18.539628 2019] [mpm_prefork:notice] [pid 6356] AH00163: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_wsgi/3.4 Python/2.7.5 configured -- resuming normal operations
[Thu May 09 20:04:18.539780 2019] [core:notice] [pid 6356] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Thu May 09 20:04:19.800795 2019] [:error] [pid 6357] [client 10.10.3.2:40850] mod_wsgi (pid=6357): Exception occurred processing WSGI script '/var/www/cgi-bin/ex6.py'.
[Thu May 09 20:04:19.800900 2019] [:error] [pid 6357] [client 10.10.3.2:40850] Traceback (most recent call last):
[Thu May 09 20:04:19.800941 2019] [:error] [pid 6357] [client 10.10.3.2:40850]   File "/var/www/cgi-bin/ex6.py", line 122, in application
[Thu May 09 20:04:19.801180 2019] [:error] [pid 6357] [client 10.10.3.2:40850]     make_database()
[Thu May 09 20:04:19.801202 2019] [:error] [pid 6357] [client 10.10.3.2:40850]   File "/var/www/cgi-bin/ex6.py", line 11, in make_database
[Thu May 09 20:04:19.801236 2019] [:error] [pid 6357] [client 10.10.3.2:40850]     con = sqlite3.connect(dbname)
[Thu May 09 20:04:19.801270 2019] [:error] [pid 6357] [client 10.10.3.2:40850] OperationalError: unable to open database file
[Thu May 09 20:19:23.275749 2019] [mpm_prefork:notice] [pid 6356] AH00170: caught SIGWINCH, shutting down gracefully
[Thu May 09 20:19:24.430462 2019] [core:notice] [pid 6404] SELinux policy enabled; httpd running as context system_u:system_r:httpd_t:s0
[Thu May 09 20:19:24.432090 2019] [suexec:notice] [pid 6404] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Thu May 09 20:19:24.483920 2019] [auth_digest:notice] [pid 6404] AH01757: generating secret for digest authentication ...
[Thu May 09 20:19:24.485452 2019] [lbmethod_heartbeat:notice] [pid 6404] AH02282: No slotmem from mod_heartmonitor
[Thu May 09 20:19:24.499308 2019] [mpm_prefork:notice] [pid 6404] AH00163: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_wsgi/3.4 Python/2.7.5 configured -- resuming normal operations
[Thu May 09 20:19:24.499430 2019] [core:notice] [pid 6404] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Thu May 09 20:19:47.242092 2019] [:error] [pid 6406] [client 10.10.3.2:40878] mod_wsgi (pid=6406): Exception occurred processing WSGI script '/var/www/cgi-bin/ex6.py'., referer: http://icesc11/
[Thu May 09 20:19:47.242188 2019] [:error] [pid 6406] [client 10.10.3.2:40878] Traceback (most recent call last):, referer: http://icesc11/
[Thu May 09 20:19:47.242235 2019] [:error] [pid 6406] [client 10.10.3.2:40878]   File "/var/www/cgi-bin/ex6.py", line 192, in application, referer: http://icesc11/
[Thu May 09 20:19:47.242470 2019] [:error] [pid 6406] [client 10.10.3.2:40878]     con = sqlite3.connect(dbname), referer: http://icesc11/
[Thu May 09 20:19:47.242512 2019] [:error] [pid 6406] [client 10.10.3.2:40878] OperationalError: unable to open database file, referer: http://icesc11/
[Thu May 09 20:20:14.703740 2019] [:error] [pid 6408] [client 10.10.3.2:40882] mod_wsgi (pid=6408): Exception occurred processing WSGI script '/var/www/cgi-bin/ex6.py'., referer: http://icesc11/
[Thu May 09 20:20:14.703844 2019] [:error] [pid 6408] [client 10.10.3.2:40882] Traceback (most recent call last):, referer: http://icesc11/
[Thu May 09 20:20:14.703893 2019] [:error] [pid 6408] [client 10.10.3.2:40882]   File "/var/www/cgi-bin/ex6.py", line 192, in application, referer: http://icesc11/
[Thu May 09 20:20:14.704125 2019] [:error] [pid 6408] [client 10.10.3.2:40882]     con = sqlite3.connect(dbname), referer: http://icesc11/
[Thu May 09 20:20:14.704165 2019] [:error] [pid 6408] [client 10.10.3.2:40882] OperationalError: unable to open database file, referer: http://icesc11/
[Thu May 09 20:20:22.361687 2019] [:error] [pid 6407] [client 10.10.3.2:40884] mod_wsgi (pid=6407): Exception occurred processing WSGI script '/var/www/cgi-bin/ex6.py'., referer: http://icesc11/
[Thu May 09 20:20:22.361784 2019] [:error] [pid 6407] [client 10.10.3.2:40884] Traceback (most recent call last):, referer: http://icesc11/
[Thu May 09 20:20:22.361829 2019] [:error] [pid 6407] [client 10.10.3.2:40884]   File "/var/www/cgi-bin/ex6.py", line 192, in application, referer: http://icesc11/
[Thu May 09 20:20:22.362059 2019] [:error] [pid 6407] [client 10.10.3.2:40884]     con = sqlite3.connect(dbname), referer: http://icesc11/
[Thu May 09 20:20:22.362096 2019] [:error] [pid 6407] [client 10.10.3.2:40884] OperationalError: unable to open database file, referer: http://icesc11/
[Thu May 09 20:21:22.451822 2019] [:error] [pid 6409] [client 10.10.3.2:40896] mod_wsgi (pid=6409): Exception occurred processing WSGI script '/var/www/cgi-bin/ex6.py'., referer: http://icesc11/
[Thu May 09 20:21:22.451929 2019] [:error] [pid 6409] [client 10.10.3.2:40896] Traceback (most recent call last):, referer: http://icesc11/
[Thu May 09 20:21:22.451977 2019] [:error] [pid 6409] [client 10.10.3.2:40896]   File "/var/www/cgi-bin/ex6.py", line 192, in application, referer: http://icesc11/
[Thu May 09 20:21:22.452214 2019] [:error] [pid 6409] [client 10.10.3.2:40896]     con = sqlite3.connect(dbname), referer: http://icesc11/
[Thu May 09 20:21:22.452257 2019] [:error] [pid 6409] [client 10.10.3.2:40896] OperationalError: unable to open database file, referer: http://icesc11/
[Thu May 09 20:21:57.814770 2019] [:error] [pid 6410] [client 10.10.3.2:40898] mod_wsgi (pid=6410): Exception occurred processing WSGI script '/var/www/cgi-bin/ex6.py'., referer: http://icesc11/
[Thu May 09 20:21:57.814877 2019] [:error] [pid 6410] [client 10.10.3.2:40898] Traceback (most recent call last):, referer: http://icesc11/
[Thu May 09 20:21:57.814925 2019] [:error] [pid 6410] [client 10.10.3.2:40898]   File "/var/www/cgi-bin/ex6.py", line 192, in application, referer: http://icesc11/
[Thu May 09 20:21:57.815169 2019] [:error] [pid 6410] [client 10.10.3.2:40898]     con = sqlite3.connect(dbname), referer: http://icesc11/
[Thu May 09 20:21:57.815210 2019] [:error] [pid 6410] [client 10.10.3.2:40898] OperationalError: unable to open database file, referer: http://icesc11/
[Thu May 09 20:24:06.679627 2019] [:error] [pid 6406] [client 10.10.3.2:40904] mod_wsgi (pid=6406): Exception occurred processing WSGI script '/var/www/cgi-bin/ex6.py'., referer: http://icesc11/
[Thu May 09 20:24:06.679817 2019] [:error] [pid 6406] [client 10.10.3.2:40904] Traceback (most recent call last):, referer: http://icesc11/
[Thu May 09 20:24:06.679897 2019] [:error] [pid 6406] [client 10.10.3.2:40904]   File "/var/www/cgi-bin/ex6.py", line 192, in application, referer: http://icesc11/
[Thu May 09 20:24:06.680006 2019] [:error] [pid 6406] [client 10.10.3.2:40904]     con = sqlite3.connect(dbname), referer: http://icesc11/
[Thu May 09 20:24:06.680079 2019] [:error] [pid 6406] [client 10.10.3.2:40904] OperationalError: unable to open database file, referer: http://icesc11/
[Thu May 09 20:24:10.520477 2019] [:error] [pid 6408] [client 10.10.3.2:40908] mod_wsgi (pid=6408): Exception occurred processing WSGI script '/var/www/cgi-bin/ex6.py'., referer: http://icesc11/
[Thu May 09 20:24:10.520633 2019] [:error] [pid 6408] [client 10.10.3.2:40908] Traceback (most recent call last):, referer: http://icesc11/
[Thu May 09 20:24:10.520751 2019] [:error] [pid 6408] [client 10.10.3.2:40908]   File "/var/www/cgi-bin/ex6.py", line 192, in application, referer: http://icesc11/
[Thu May 09 20:24:10.520871 2019] [:error] [pid 6408] [client 10.10.3.2:40908]     con = sqlite3.connect(dbname), referer: http://icesc11/
[Thu May 09 20:24:10.520944 2019] [:error] [pid 6408] [client 10.10.3.2:40908] OperationalError: unable to open database file, referer: http://icesc11/
[Thu May 09 20:25:24.855952 2019] [mpm_prefork:notice] [pid 6404] AH00170: caught SIGWINCH, shutting down gracefully
[Thu May 09 20:25:26.013516 2019] [core:notice] [pid 6443] SELinux policy enabled; httpd running as context system_u:system_r:httpd_t:s0
[Thu May 09 20:25:26.015408 2019] [suexec:notice] [pid 6443] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Thu May 09 20:25:26.071332 2019] [auth_digest:notice] [pid 6443] AH01757: generating secret for digest authentication ...
[Thu May 09 20:25:26.073949 2019] [lbmethod_heartbeat:notice] [pid 6443] AH02282: No slotmem from mod_heartmonitor
[Thu May 09 20:25:26.087192 2019] [mpm_prefork:notice] [pid 6443] AH00163: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_wsgi/3.4 Python/2.7.5 configured -- resuming normal operations
[Thu May 09 20:25:26.087299 2019] [core:notice] [pid 6443] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Thu May 09 20:25:33.180641 2019] [:error] [pid 6444] [client 10.10.3.2:40910] mod_wsgi (pid=6444): Exception occurred processing WSGI script '/var/www/cgi-bin/ex6.py'., referer: http://icesc11/
[Thu May 09 20:25:33.180761 2019] [:error] [pid 6444] [client 10.10.3.2:40910] Traceback (most recent call last):, referer: http://icesc11/
[Thu May 09 20:25:33.180809 2019] [:error] [pid 6444] [client 10.10.3.2:40910]   File "/var/www/cgi-bin/ex6.py", line 192, in application, referer: http://icesc11/
[Thu May 09 20:25:33.181046 2019] [:error] [pid 6444] [client 10.10.3.2:40910]     con = sqlite3.connect(dbname), referer: http://icesc11/
[Thu May 09 20:25:33.181086 2019] [:error] [pid 6444] [client 10.10.3.2:40910] OperationalError: unable to open database file, referer: http://icesc11/
[Thu May 09 20:27:55.702050 2019] [:error] [pid 6445] [client 10.10.3.2:40914] mod_wsgi (pid=6445): Exception occurred processing WSGI script '/var/www/cgi-bin/ex6.py'., referer: http://icesc11/
[Thu May 09 20:27:55.702225 2019] [:error] [pid 6445] [client 10.10.3.2:40914] Traceback (most recent call last):, referer: http://icesc11/
[Thu May 09 20:27:55.702327 2019] [:error] [pid 6445] [client 10.10.3.2:40914]   File "/var/www/cgi-bin/ex6.py", line 192, in application, referer: http://icesc11/
[Thu May 09 20:27:55.702863 2019] [:error] [pid 6445] [client 10.10.3.2:40914]     con = sqlite3.connect(dbname), referer: http://icesc11/
[Thu May 09 20:27:55.702983 2019] [:error] [pid 6445] [client 10.10.3.2:40914] OperationalError: unable to open database file, referer: http://icesc11/
[Thu May 09 20:31:17.922317 2019] [mpm_prefork:notice] [pid 6443] AH00170: caught SIGWINCH, shutting down gracefully
[Thu May 09 20:31:19.079008 2019] [core:notice] [pid 6466] SELinux policy enabled; httpd running as context system_u:system_r:httpd_t:s0
[Thu May 09 20:31:19.081279 2019] [suexec:notice] [pid 6466] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Thu May 09 20:31:19.158985 2019] [auth_digest:notice] [pid 6466] AH01757: generating secret for digest authentication ...
[Thu May 09 20:31:19.161644 2019] [lbmethod_heartbeat:notice] [pid 6466] AH02282: No slotmem from mod_heartmonitor
[Thu May 09 20:31:19.174026 2019] [mpm_prefork:notice] [pid 6466] AH00163: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_wsgi/3.4 Python/2.7.5 configured -- resuming normal operations
[Thu May 09 20:31:19.174121 2019] [core:notice] [pid 6466] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Thu May 09 20:31:33.007796 2019] [:error] [pid 6467] [client 10.10.3.2:40922] mod_wsgi (pid=6467): Exception occurred processing WSGI script '/var/www/cgi-bin/ex6.py'., referer: http://icesc11/
[Thu May 09 20:31:33.007943 2019] [:error] [pid 6467] [client 10.10.3.2:40922] Traceback (most recent call last):, referer: http://icesc11/
[Thu May 09 20:31:33.008021 2019] [:error] [pid 6467] [client 10.10.3.2:40922]   File "/var/www/cgi-bin/ex6.py", line 206, in application, referer: http://icesc11/
[Thu May 09 20:31:33.008422 2019] [:error] [pid 6467] [client 10.10.3.2:40922]     for row in cur.execute(search_read):, referer: http://icesc11/
[Thu May 09 20:31:33.008495 2019] [:error] [pid 6467] [client 10.10.3.2:40922] OperationalError: no such column: bookid, referer: http://icesc11/
[Thu May 09 20:37:10.685282 2019] [mpm_prefork:notice] [pid 6466] AH00170: caught SIGWINCH, shutting down gracefully
[Thu May 09 20:37:11.841730 2019] [core:notice] [pid 6505] SELinux policy enabled; httpd running as context system_u:system_r:httpd_t:s0
[Thu May 09 20:37:11.843346 2019] [suexec:notice] [pid 6505] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Thu May 09 20:37:11.895057 2019] [auth_digest:notice] [pid 6505] AH01757: generating secret for digest authentication ...
[Thu May 09 20:37:11.896416 2019] [lbmethod_heartbeat:notice] [pid 6505] AH02282: No slotmem from mod_heartmonitor
[Thu May 09 20:37:11.908356 2019] [mpm_prefork:notice] [pid 6505] AH00163: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_wsgi/3.4 Python/2.7.5 configured -- resuming normal operations
[Thu May 09 20:37:11.908480 2019] [core:notice] [pid 6505] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Thu May 09 20:37:17.506860 2019] [:error] [pid 6506] [client 10.10.3.2:41086] mod_wsgi (pid=6506): Exception occurred processing WSGI script '/var/www/cgi-bin/ex6.py'., referer: http://icesc11/
[Thu May 09 20:37:17.506955 2019] [:error] [pid 6506] [client 10.10.3.2:41086] Traceback (most recent call last):, referer: http://icesc11/
[Thu May 09 20:37:17.506993 2019] [:error] [pid 6506] [client 10.10.3.2:41086]   File "/var/www/cgi-bin/ex6.py", line 274, in application, referer: http://icesc11/
[Thu May 09 20:37:17.507219 2019] [:error] [pid 6506] [client 10.10.3.2:41086]     html = html.encode('utf-8'), referer: http://icesc11/
[Thu May 09 20:37:17.507264 2019] [:error] [pid 6506] [client 10.10.3.2:41086] UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 382: ordinal not in range(128), referer: http://icesc11/
[Thu May 09 20:37:21.179221 2019] [:error] [pid 6507] [client 10.10.3.2:41088] mod_wsgi (pid=6507): Exception occurred processing WSGI script '/var/www/cgi-bin/ex6.py'., referer: http://icesc11/
[Thu May 09 20:37:21.179381 2019] [:error] [pid 6507] [client 10.10.3.2:41088] Traceback (most recent call last):, referer: http://icesc11/
[Thu May 09 20:37:21.179446 2019] [:error] [pid 6507] [client 10.10.3.2:41088]   File "/var/www/cgi-bin/ex6.py", line 274, in application, referer: http://icesc11/
[Thu May 09 20:37:21.179859 2019] [:error] [pid 6507] [client 10.10.3.2:41088]     html = html.encode('utf-8'), referer: http://icesc11/
[Thu May 09 20:37:21.179947 2019] [:error] [pid 6507] [client 10.10.3.2:41088] UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 382: ordinal not in range(128), referer: http://icesc11/
[Thu May 09 20:38:12.707786 2019] [mpm_prefork:notice] [pid 6505] AH00170: caught SIGWINCH, shutting down gracefully
[Thu May 09 20:38:13.866083 2019] [core:notice] [pid 6528] SELinux policy enabled; httpd running as context system_u:system_r:httpd_t:s0
[Thu May 09 20:38:13.867755 2019] [suexec:notice] [pid 6528] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Thu May 09 20:38:13.921908 2019] [auth_digest:notice] [pid 6528] AH01757: generating secret for digest authentication ...
[Thu May 09 20:38:13.923283 2019] [lbmethod_heartbeat:notice] [pid 6528] AH02282: No slotmem from mod_heartmonitor
[Thu May 09 20:38:13.934106 2019] [mpm_prefork:notice] [pid 6528] AH00163: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_wsgi/3.4 Python/2.7.5 configured -- resuming normal operations
[Thu May 09 20:38:13.934213 2019] [core:notice] [pid 6528] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Thu May 09 20:38:34.002464 2019] [:error] [pid 6531] [client 10.10.3.2:41096] mod_wsgi (pid=6531): Exception occurred processing WSGI script '/var/www/cgi-bin/ex6.py'., referer: http://icesc11/?n=111&update=update
[Thu May 09 20:38:34.002673 2019] [:error] [pid 6531] [client 10.10.3.2:41096] Traceback (most recent call last):, referer: http://icesc11/?n=111&update=update
[Thu May 09 20:38:34.002758 2019] [:error] [pid 6531] [client 10.10.3.2:41096]   File "/var/www/cgi-bin/ex6.py", line 258, in application, referer: http://icesc11/?n=111&update=update
[Thu May 09 20:38:34.003176 2019] [:error] [pid 6531] [client 10.10.3.2:41096]     '<td><input type="text" name="'  +str(row[1])+  '" value="' + str(row[2]) + '"></td>\\n'\\, referer: http://icesc11/?n=111&update=update
[Thu May 09 20:38:34.003265 2019] [:error] [pid 6531] [client 10.10.3.2:41096] UnicodeEncodeError: 'ascii' codec can't encode character u'\\u5ead' in position 0: ordinal not in range(128), referer: http://icesc11/?n=111&update=update
[Thu May 09 20:42:29.890697 2019] [mpm_prefork:notice] [pid 6528] AH00170: caught SIGWINCH, shutting down gracefully
[Thu May 09 20:42:31.040837 2019] [core:notice] [pid 6549] SELinux policy enabled; httpd running as context system_u:system_r:httpd_t:s0
[Thu May 09 20:42:31.042410 2019] [suexec:notice] [pid 6549] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Thu May 09 20:42:31.094868 2019] [auth_digest:notice] [pid 6549] AH01757: generating secret for digest authentication ...
[Thu May 09 20:42:31.096184 2019] [lbmethod_heartbeat:notice] [pid 6549] AH02282: No slotmem from mod_heartmonitor
[Thu May 09 20:42:31.109620 2019] [mpm_prefork:notice] [pid 6549] AH00163: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_wsgi/3.4 Python/2.7.5 configured -- resuming normal operations
[Thu May 09 20:42:31.109753 2019] [core:notice] [pid 6549] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Thu May 09 20:42:47.588558 2019] [:error] [pid 6551] [client 10.10.3.2:41108] mod_wsgi (pid=6551): Exception occurred processing WSGI script '/var/www/cgi-bin/ex6.py'., referer: http://icesc11/?n=111&update=update
[Thu May 09 20:42:47.588706 2019] [:error] [pid 6551] [client 10.10.3.2:41108] Traceback (most recent call last):, referer: http://icesc11/?n=111&update=update
[Thu May 09 20:42:47.588780 2019] [:error] [pid 6551] [client 10.10.3.2:41108]   File "/var/www/cgi-bin/ex6.py", line 258, in application, referer: http://icesc11/?n=111&update=update
[Thu May 09 20:42:47.589041 2019] [:error] [pid 6551] [client 10.10.3.2:41108]     '<td><input type="text" name="'+str(row[1])+ '" value="'+ str(row[2])+'"></td>\\n'\\, referer: http://icesc11/?n=111&update=update
[Thu May 09 20:42:47.589091 2019] [:error] [pid 6551] [client 10.10.3.2:41108] UnicodeEncodeError: 'ascii' codec can't encode character u'\\u5ead' in position 0: ordinal not in range(128), referer: http://icesc11/?n=111&update=update
[Thu May 09 20:42:51.031144 2019] [mpm_prefork:notice] [pid 6549] AH00170: caught SIGWINCH, shutting down gracefully
[Thu May 09 20:42:52.186139 2019] [core:notice] [pid 6566] SELinux policy enabled; httpd running as context system_u:system_r:httpd_t:s0
[Thu May 09 20:42:52.188614 2019] [suexec:notice] [pid 6566] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Thu May 09 20:42:52.269583 2019] [auth_digest:notice] [pid 6566] AH01757: generating secret for digest authentication ...
[Thu May 09 20:42:52.272006 2019] [lbmethod_heartbeat:notice] [pid 6566] AH02282: No slotmem from mod_heartmonitor
[Thu May 09 20:42:52.286353 2019] [mpm_prefork:notice] [pid 6566] AH00163: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_wsgi/3.4 Python/2.7.5 configured -- resuming normal operations
[Thu May 09 20:42:52.286465 2019] [core:notice] [pid 6566] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Thu May 09 20:43:26.669978 2019] [:error] [pid 6567] [client 10.10.3.2:41120] mod_wsgi (pid=6567): Exception occurred processing WSGI script '/var/www/cgi-bin/ex6.py'., referer: http://icesc11/?n=111&update=update
[Thu May 09 20:43:26.670121 2019] [:error] [pid 6567] [client 10.10.3.2:41120] Traceback (most recent call last):, referer: http://icesc11/?n=111&update=update
[Thu May 09 20:43:26.670172 2019] [:error] [pid 6567] [client 10.10.3.2:41120]   File "/var/www/cgi-bin/ex6.py", line 258, in application, referer: http://icesc11/?n=111&update=update
[Thu May 09 20:43:26.670429 2019] [:error] [pid 6567] [client 10.10.3.2:41120]     '<td><input type="text" name="'+str(row[1])+ '" value="'+ str(row[2])+'"></td>\\n'\\, referer: http://icesc11/?n=111&update=update
[Thu May 09 20:43:26.670478 2019] [:error] [pid 6567] [client 10.10.3.2:41120] UnicodeEncodeError: 'ascii' codec can't encode character u'\\u5ead' in position 0: ordinal not in range(128), referer: http://icesc11/?n=111&update=update
[Thu May 09 20:48:04.966583 2019] [mpm_prefork:notice] [pid 6566] AH00170: caught SIGWINCH, shutting down gracefully
[Thu May 09 20:48:06.124549 2019] [core:notice] [pid 6606] SELinux policy enabled; httpd running as context system_u:system_r:httpd_t:s0
[Thu May 09 20:48:06.128122 2019] [suexec:notice] [pid 6606] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Thu May 09 20:48:06.207221 2019] [auth_digest:notice] [pid 6606] AH01757: generating secret for digest authentication ...
[Thu May 09 20:48:06.208868 2019] [lbmethod_heartbeat:notice] [pid 6606] AH02282: No slotmem from mod_heartmonitor
[Thu May 09 20:48:06.222648 2019] [mpm_prefork:notice] [pid 6606] AH00163: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_wsgi/3.4 Python/2.7.5 configured -- resuming normal operations
[Thu May 09 20:48:06.222827 2019] [core:notice] [pid 6606] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Thu May 09 20:48:09.073943 2019] [:error] [pid 6607] [client 10.10.3.2:41134] mod_wsgi (pid=6607): Exception occurred processing WSGI script '/var/www/cgi-bin/ex6.py'., referer: http://icesc11/?n=111&update=update
[Thu May 09 20:48:09.074080 2019] [:error] [pid 6607] [client 10.10.3.2:41134] Traceback (most recent call last):, referer: http://icesc11/?n=111&update=update
[Thu May 09 20:48:09.074126 2019] [:error] [pid 6607] [client 10.10.3.2:41134]   File "/var/www/cgi-bin/ex6.py", line 258, in application, referer: http://icesc11/?n=111&update=update
[Thu May 09 20:48:09.074405 2019] [:error] [pid 6607] [client 10.10.3.2:41134]     '<td><input type="text" name="'+str(row[1])+ '" value="'+ str(row[2])+'"></td>\\n'\\, referer: http://icesc11/?n=111&update=update
[Thu May 09 20:48:09.074455 2019] [:error] [pid 6607] [client 10.10.3.2:41134] UnicodeEncodeError: 'ascii' codec can't encode character u'\\u5ead' in position 0: ordinal not in range(128), referer: http://icesc11/?n=111&update=update
[Thu May 09 20:52:01.631569 2019] [mpm_prefork:notice] [pid 6606] AH00170: caught SIGWINCH, shutting down gracefully
[Thu May 09 20:52:02.784488 2019] [core:notice] [pid 6746] SELinux policy enabled; httpd running as context system_u:system_r:httpd_t:s0
[Thu May 09 20:52:02.786308 2019] [suexec:notice] [pid 6746] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Thu May 09 20:52:02.838794 2019] [auth_digest:notice] [pid 6746] AH01757: generating secret for digest authentication ...
[Thu May 09 20:52:02.840121 2019] [lbmethod_heartbeat:notice] [pid 6746] AH02282: No slotmem from mod_heartmonitor
[Thu May 09 20:52:02.853180 2019] [mpm_prefork:notice] [pid 6746] AH00163: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_wsgi/3.4 Python/2.7.5 configured -- resuming normal operations
[Thu May 09 20:52:02.853285 2019] [core:notice] [pid 6746] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Thu May 09 20:54:37.863102 2019] [mpm_prefork:notice] [pid 6746] AH00170: caught SIGWINCH, shutting down gracefully
[Thu May 09 20:54:39.015584 2019] [core:notice] [pid 6765] SELinux policy enabled; httpd running as context system_u:system_r:httpd_t:s0
[Thu May 09 20:54:39.017258 2019] [suexec:notice] [pid 6765] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Thu May 09 20:54:39.072370 2019] [auth_digest:notice] [pid 6765] AH01757: generating secret for digest authentication ...
[Thu May 09 20:54:39.073752 2019] [lbmethod_heartbeat:notice] [pid 6765] AH02282: No slotmem from mod_heartmonitor
[Thu May 09 20:54:39.087188 2019] [mpm_prefork:notice] [pid 6765] AH00163: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_wsgi/3.4 Python/2.7.5 configured -- resuming normal operations
[Thu May 09 20:54:39.087292 2019] [core:notice] [pid 6765] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Thu May 09 20:54:39.283399 2019] [:error] [pid 6766] ('111', '0')
[Thu May 09 20:55:21.983799 2019] [mpm_prefork:notice] [pid 6765] AH00170: caught SIGWINCH, shutting down gracefully
[Thu May 09 20:55:23.138294 2019] [core:notice] [pid 6802] SELinux policy enabled; httpd running as context system_u:system_r:httpd_t:s0
[Thu May 09 20:55:23.140271 2019] [suexec:notice] [pid 6802] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Thu May 09 20:55:23.223146 2019] [auth_digest:notice] [pid 6802] AH01757: generating secret for digest authentication ...
[Thu May 09 20:55:23.225536 2019] [lbmethod_heartbeat:notice] [pid 6802] AH02282: No slotmem from mod_heartmonitor
[Thu May 09 20:55:23.239023 2019] [mpm_prefork:notice] [pid 6802] AH00163: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_wsgi/3.4 Python/2.7.5 configured -- resuming normal operations
[Thu May 09 20:55:23.239146 2019] [core:notice] [pid 6802] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Thu May 09 20:55:26.009872 2019] [:error] [pid 6803] [client 10.10.3.2:41152] mod_wsgi (pid=6803): Exception occurred processing WSGI script '/var/www/cgi-bin/ex6.py'., referer: http://icesc11/?update2=update
[Thu May 09 20:55:26.010008 2019] [:error] [pid 6803] [client 10.10.3.2:41152] Traceback (most recent call last):, referer: http://icesc11/?update2=update
[Thu May 09 20:55:26.010055 2019] [:error] [pid 6803] [client 10.10.3.2:41152]   File "/var/www/cgi-bin/ex6.py", line 259, in application, referer: http://icesc11/?update2=update
[Thu May 09 20:55:26.010320 2019] [:error] [pid 6803] [client 10.10.3.2:41152]     '<td><input type="text" name="'+str(row[1]).encode('utf-8')+ '" value="'+ str(row[2]).encode('utf-8')+'"></td>\\n'\\, referer: http://icesc11/?update2=update
[Thu May 09 20:55:26.010377 2019] [:error] [pid 6803] [client 10.10.3.2:41152] UnicodeEncodeError: 'ascii' codec can't encode character u'\\u5ead' in position 0: ordinal not in range(128), referer: http://icesc11/?update2=update
[Thu May 09 20:56:52.313211 2019] [mpm_prefork:notice] [pid 6802] AH00170: caught SIGWINCH, shutting down gracefully
[Thu May 09 21:06:26.460843 2019] [core:notice] [pid 4455] SELinux policy enabled; httpd running as context system_u:system_r:httpd_t:s0
[Thu May 09 21:06:26.465174 2019] [suexec:notice] [pid 4455] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using www1.ice.nuie.nagoya-u.ac.jp. Set the 'ServerName' directive globally to suppress this message
[Thu May 09 21:06:26.510086 2019] [auth_digest:notice] [pid 4455] AH01757: generating secret for digest authentication ...
[Thu May 09 21:06:26.512252 2019] [lbmethod_heartbeat:notice] [pid 4455] AH02282: No slotmem from mod_heartmonitor
[Thu May 09 21:06:26.520576 2019] [mpm_prefork:notice] [pid 4455] AH00163: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_wsgi/3.4 Python/2.7.5 configured -- resuming normal operations
[Thu May 09 21:06:26.521406 2019] [core:notice] [pid 4455] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
